# Generated by Django 5.1.2 on 2024-11-04 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(editable=False, max_length=15, unique=True)),
                ('incident_type', models.CharField(choices=[('ENTERPRISE', 'Enterprise'), ('GOVERNMENT', 'Government')], max_length=20)),
                ('reporter_name', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], default='Open', max_length=15)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_date'],
            },
        ),
    ]
