# Generated by Django 5.1.2 on 2024-11-04 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Enter a valid phone number.', max_length=15)),
                ('address', models.TextField(help_text='Enter the complete address.')),
                ('pincode', models.CharField(help_text='Enter the postal code.', max_length=10)),
                ('city', models.CharField(help_text='Enter the city name.', max_length=100)),
                ('country', models.CharField(help_text='Enter the country name.', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
